export const curatedProducts = [

  // ─────────────────────────────────────────────
  // WATCHES
  // ─────────────────────────────────────────────
  {
    _id: 'watch-201',
    name: 'Apple Watch Series 9 GPS 45mm Midnight',
    image: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?q=80&w=800&auto=format&fit=crop',
    description: 'Advanced health tracking, S9 SiP processor, double tap gesture control, and crystal Retina display.',
    category: 'Watches',
    brand: 'Apple',
    price: 399.99,
    originalPrice: 429.99,
    discount: 7,
    rating: 4.9,
    numReviews: 320,
    countInStock: 15,
    tags: ['watches', 'smartwatch', 'apple', 'fitness', 'tech'],
  },
  {
    _id: 'watch-202',
    name: 'Fossil Neuautra Automatic Chronograph Leather Watch',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=800&auto=format&fit=crop',
    description: 'Timeless stainless steel case with blue sunray dial and rich genuine brown leather strap.',
    category: 'Watches',
    brand: 'Fossil',
    price: 149.99,
    originalPrice: 199.99,
    discount: 25,
    rating: 4.8,
    numReviews: 175,
    countInStock: 20,
    tags: ['watches', 'chronograph', 'fossil', 'leather', 'luxury'],
  },
  {
    _id: 'watch-203',
    name: 'Casio G-Shock Tough Solar Waterproof Digital Watch',
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=800&auto=format&fit=crop',
    description: 'Shock-resistant 200m water-resistant tactical outdoor watch with solar power tech.',
    category: 'Watches',
    brand: 'Casio',
    price: 99.99,
    originalPrice: 129.99,
    discount: 23,
    rating: 4.9,
    numReviews: 430,
    countInStock: 30,
    tags: ['watches', 'gshock', 'casio', 'digital', 'waterproof'],
  },
  {
    _id: 'watch-204',
    name: 'Seiko Presage Cocktail Time Automatic Watch',
    image: 'https://images.unsplash.com/photo-1533136512052-a66e1cdcebf7?q=80&w=800&auto=format&fit=crop',
    description: 'Award-winning Japanese automatic movement with stunning enamel cocktail dial.',
    category: 'Watches',
    brand: 'Seiko',
    price: 395.00,
    originalPrice: 449.00,
    discount: 12,
    rating: 4.8,
    numReviews: 200,
    countInStock: 8,
    tags: ['watches', 'automatic', 'seiko', 'luxury', 'japanese'],
  },
  {
    _id: 'watch-205',
    name: 'Rolex Submariner Date Automatic Oyster Watch',
    image: 'https://images.unsplash.com/photo-1547996160-81dfa63595aa?q=80&w=800&auto=format&fit=crop',
    description: 'Iconic Swiss diving watch with ceramic bezel, Oystersteel bracelet, and 300m water resistance.',
    category: 'Watches',
    brand: 'Rolex',
    price: 8999.00,
    originalPrice: 9999.00,
    discount: 10,
    rating: 5.0,
    numReviews: 85,
    countInStock: 3,
    tags: ['watches', 'luxury', 'rolex', 'swiss', 'diving'],
  },
  {
    _id: 'watch-206',
    name: 'Samsung Galaxy Watch 6 Classic 47mm',
    image: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?q=80&w=800&auto=format&fit=crop',
    description: 'Rotating bezel design with advanced health tracking and Wear OS by Samsung.',
    category: 'Watches',
    brand: 'Samsung',
    price: 299.99,
    originalPrice: 349.99,
    discount: 14,
    rating: 4.7,
    numReviews: 260,
    countInStock: 18,
    tags: ['watches', 'smartwatch', 'samsung', 'android', 'fitness'],
  },

  // ─────────────────────────────────────────────
  // COSMETICS & SKINCARE
  // ─────────────────────────────────────────────
  {
    _id: 'cosm-301',
    name: 'The Ordinary Hyaluronic Acid 2% + B5 Serum',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=800&auto=format&fit=crop',
    description: 'Multi-depth hydration formula with low, medium, and high molecular weight hyaluronic acid.',
    category: 'Cosmetics',
    brand: 'The Ordinary',
    price: 14.50,
    originalPrice: 19.99,
    discount: 27,
    rating: 4.8,
    numReviews: 580,
    countInStock: 40,
    tags: ['skincare', 'serum', 'hyaluronic', 'cosmetics', 'beauty'],
  },
  {
    _id: 'cosm-302',
    name: 'MAC Matte Velvet Lipstick – Ruby Woo',
    image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?q=80&w=800&auto=format&fit=crop',
    description: 'Iconic vivid blue-red lipstick with intense color payoff and non-drying retro matte finish.',
    category: 'Cosmetics',
    brand: 'MAC',
    price: 19.99,
    originalPrice: 23.00,
    discount: 13,
    rating: 4.9,
    numReviews: 750,
    countInStock: 30,
    tags: ['cosmetics', 'lipstick', 'makeup', 'beauty', 'mac'],
  },
  {
    _id: 'cosm-303',
    name: 'Real Techniques Professional Makeup Brush Set (5 Pcs)',
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?q=80&w=800&auto=format&fit=crop',
    description: 'UltraPlush cruelty-free synthetic bristles for seamless apply of foundation and blush.',
    category: 'Cosmetics',
    brand: 'Real Techniques',
    price: 17.99,
    originalPrice: 24.99,
    discount: 28,
    rating: 4.7,
    numReviews: 310,
    countInStock: 35,
    tags: ['makeup brush', 'brush kit', 'cosmetics', 'beauty tool'],
  },
  {
    _id: 'cosm-304',
    name: "L'Oreal Paris True Match Liquid Foundation",
    image: 'https://images.unsplash.com/photo-1631214524020-3c69b7cce811?q=80&w=800&auto=format&fit=crop',
    description: "Buildable coverage foundation matched to skin's unique tone for a natural, skin-like finish.",
    category: 'Cosmetics',
    brand: "L'Oreal",
    price: 10.99,
    originalPrice: 14.99,
    discount: 26,
    rating: 4.6,
    numReviews: 890,
    countInStock: 50,
    tags: ['foundation', 'makeup', 'cosmetics', 'loreal', 'beauty'],
  },
  {
    _id: 'cosm-305',
    name: 'Charlotte Tilbury Magic Cream Moisturiser (50ml)',
    image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?q=80&w=800&auto=format&fit=crop',
    description: 'Luxury anti-aging moisturiser with 8-hour hydration, hyaluronic acid & vitamins C and E.',
    category: 'Cosmetics',
    brand: 'Charlotte Tilbury',
    price: 89.99,
    originalPrice: 105.00,
    discount: 14,
    rating: 4.9,
    numReviews: 420,
    countInStock: 20,
    tags: ['skincare', 'moisturiser', 'cosmetics', 'anti-aging', 'luxury'],
  },
  {
    _id: 'cosm-306',
    name: 'Maybelline Sky High Waterproof Mascara',
    image: 'https://images.unsplash.com/photo-1512207736890-6ffed8a84e8d?q=80&w=800&auto=format&fit=crop',
    description: 'Flexible wand and buildable formula for sky-high defined lashes with all-day waterproof wear.',
    category: 'Cosmetics',
    brand: 'Maybelline',
    price: 9.49,
    originalPrice: 12.99,
    discount: 27,
    rating: 4.7,
    numReviews: 1100,
    countInStock: 60,
    tags: ['mascara', 'makeup', 'cosmetics', 'maybelline', 'beauty'],
  },
  {
    _id: 'cosm-307',
    name: 'Neutrogena Hydro Boost Water Gel SPF 25 (50ml)',
    image: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?q=80&w=800&auto=format&fit=crop',
    description: 'Lightweight oil-free gel with hyaluronic acid for intense 24hr hydration and SPF protection.',
    category: 'Cosmetics',
    brand: 'Neutrogena',
    price: 15.99,
    originalPrice: 20.99,
    discount: 24,
    rating: 4.8,
    numReviews: 640,
    countInStock: 45,
    tags: ['sunscreen', 'spf', 'skincare', 'cosmetics', 'hydrating'],
  },

  // ─────────────────────────────────────────────
  // CLOTHES
  // ─────────────────────────────────────────────
  {
    _id: 'cloth-401',
    name: "Levi's Classic Trucker Denim Jacket",
    image: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?q=80&w=800&auto=format&fit=crop',
    description: 'The original denim jacket since 1967. 100% heavy cotton denim with point collar.',
    category: 'Clothes',
    brand: "Levi's",
    price: 79.99,
    originalPrice: 99.99,
    discount: 20,
    rating: 4.8,
    numReviews: 340,
    countInStock: 20,
    tags: ['clothes', 'jacket', 'denim', 'levis', 'apparel', 'shirt'],
  },
  {
    _id: 'cloth-402',
    name: 'Ralph Lauren Essential Oxford Cotton Shirt',
    image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?q=80&w=800&auto=format&fit=crop',
    description: 'Tailored fit button-down oxford shirt crafted from breathable long-staple cotton.',
    category: 'Clothes',
    brand: 'Ralph Lauren',
    price: 89.99,
    originalPrice: 119.99,
    discount: 25,
    rating: 4.7,
    numReviews: 210,
    countInStock: 16,
    tags: ['clothes', 'shirt', 'formal', 'cotton', 'apparel'],
  },
  {
    _id: 'cloth-403',
    name: 'Tommy Hilfiger Slim Fit Linen Casual Shirt',
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=800&auto=format&fit=crop',
    description: 'Lightweight pure linen shirt perfect for summer and casual weekend wear.',
    category: 'Clothes',
    brand: 'Tommy Hilfiger',
    price: 49.99,
    originalPrice: 69.99,
    discount: 28,
    rating: 4.7,
    numReviews: 165,
    countInStock: 22,
    tags: ['clothes', 'shirt', 'linen', 'casual', 'apparel'],
  },
  {
    _id: 'cloth-404',
    name: "Levi's 511 Slim Fit Men's Jeans",
    image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?q=80&w=800&auto=format&fit=crop',
    description: 'Classic slim fit jeans in authentic stretch denim for all-day comfort and style.',
    category: 'Clothes',
    brand: "Levi's",
    price: 59.99,
    originalPrice: 79.99,
    discount: 25,
    rating: 4.8,
    numReviews: 490,
    countInStock: 28,
    tags: ['clothes', 'jeans', 'denim', 'levis', 'pants', 'apparel'],
  },
  {
    _id: 'cloth-405',
    name: 'Zara Premium Wool Blend Overcoat',
    image: 'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?q=80&w=800&auto=format&fit=crop',
    description: 'Luxurious wool-blend double-breasted long coat for cold weather elegance.',
    category: 'Clothes',
    brand: 'Zara',
    price: 129.99,
    originalPrice: 169.99,
    discount: 23,
    rating: 4.6,
    numReviews: 180,
    countInStock: 12,
    tags: ['clothes', 'coat', 'wool', 'winter', 'apparel'],
  },
  {
    _id: 'cloth-406',
    name: 'H&M Regular Fit Crewneck Sweatshirt',
    image: 'https://images.unsplash.com/photo-1556821840-3a63f15732ce?q=80&w=800&auto=format&fit=crop',
    description: 'Soft cotton-blend crewneck sweatshirt with brushed inside for warmth and everyday comfort.',
    category: 'Clothes',
    brand: 'H&M',
    price: 24.99,
    originalPrice: 34.99,
    discount: 28,
    rating: 4.5,
    numReviews: 380,
    countInStock: 40,
    tags: ['clothes', 'sweatshirt', 'casual', 'cotton', 'apparel'],
  },
  {
    _id: 'cloth-407',
    name: 'Nike Dri-FIT Training T-Shirt',
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=800&auto=format&fit=crop',
    description: 'Sweat-wicking Dri-FIT technology keeps you dry and comfortable during intense workouts.',
    category: 'Clothes',
    brand: 'Nike',
    price: 29.99,
    originalPrice: 39.99,
    discount: 25,
    rating: 4.7,
    numReviews: 520,
    countInStock: 50,
    tags: ['clothes', 'tshirt', 'nike', 'sportswear', 'fitness', 'apparel'],
  },
  {
    _id: 'cloth-408',
    name: 'Adidas Tiro Track Pants',
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?q=80&w=800&auto=format&fit=crop',
    description: 'Classic slim-fit track pants with two side pockets and iconic three-stripe design.',
    category: 'Clothes',
    brand: 'Adidas',
    price: 39.99,
    originalPrice: 54.99,
    discount: 27,
    rating: 4.6,
    numReviews: 285,
    countInStock: 35,
    tags: ['clothes', 'track pants', 'adidas', 'sportswear', 'apparel'],
  },

  // ─────────────────────────────────────────────
  // ACCESSORIES
  // ─────────────────────────────────────────────
  {
    _id: 'acc-501',
    name: 'Ray-Ban Wayfarer Classic Polarized Sunglasses',
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?q=80&w=800&auto=format&fit=crop',
    description: 'Iconic crystal green G-15 polarized lenses with 100% UV protection and durable black frame.',
    category: 'Accessories',
    brand: 'Ray-Ban',
    price: 139.99,
    originalPrice: 169.99,
    discount: 18,
    rating: 4.9,
    numReviews: 512,
    countInStock: 40,
    tags: ['accessories', 'sunglasses', 'ray-ban', 'eyewear', 'uv protection'],
  },
  {
    _id: 'acc-502',
    name: 'Tommy Hilfiger Reversible Genuine Leather Belt',
    image: 'https://images.unsplash.com/photo-1624222247344-550fb60583dc?q=80&w=800&auto=format&fit=crop',
    description: 'Versatile black and brown reversible leather belt with polished silver harness buckle.',
    category: 'Accessories',
    brand: 'Tommy Hilfiger',
    price: 29.99,
    originalPrice: 39.99,
    discount: 25,
    rating: 4.7,
    numReviews: 189,
    countInStock: 50,
    tags: ['accessories', 'belt', 'leather', 'formal'],
  },
  {
    _id: 'acc-503',
    name: 'Fossil RFID Blocking Leather Bifold Wallet',
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?q=80&w=800&auto=format&fit=crop',
    description: 'Handcrafted genuine leather wallet with RFID protection and multiple card slots.',
    category: 'Accessories',
    brand: 'Fossil',
    price: 34.99,
    originalPrice: 49.99,
    discount: 30,
    rating: 4.8,
    numReviews: 240,
    countInStock: 35,
    tags: ['accessories', 'wallet', 'leather', 'rfid', 'fossil'],
  },
  {
    _id: 'acc-504',
    name: "Hermès Silk Twill Scarf (90x90cm)",
    image: 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?q=80&w=800&auto=format&fit=crop',
    description: 'Iconic hand-rolled edge silk scarf with limited-edition artistic print. A timeless luxury gift.',
    category: 'Accessories',
    brand: 'Hermès',
    price: 389.99,
    originalPrice: 449.99,
    discount: 13,
    rating: 5.0,
    numReviews: 72,
    countInStock: 5,
    tags: ['accessories', 'scarf', 'silk', 'hermes', 'luxury'],
  },
  {
    _id: 'acc-505',
    name: 'Gucci GG Supreme Canvas Crossbody Bag',
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=800&auto=format&fit=crop',
    description: 'Premium GG Supreme canvas bag with leather trim and iconic double G hardware.',
    category: 'Accessories',
    brand: 'Gucci',
    price: 1150.00,
    originalPrice: 1299.00,
    discount: 11,
    rating: 4.9,
    numReviews: 95,
    countInStock: 4,
    tags: ['accessories', 'bag', 'gucci', 'luxury', 'crossbody'],
  },
  {
    _id: 'acc-506',
    name: 'Oakley Holbrook Prizm Sports Sunglasses',
    image: 'https://images.unsplash.com/photo-1574258495973-f010dfbb5371?q=80&w=800&auto=format&fit=crop',
    description: 'Prizm lens technology for enhanced color and contrast during outdoor sports.',
    category: 'Accessories',
    brand: 'Oakley',
    price: 159.99,
    originalPrice: 189.99,
    discount: 16,
    rating: 4.8,
    numReviews: 275,
    countInStock: 18,
    tags: ['accessories', 'sunglasses', 'oakley', 'sports', 'uv'],
  },
  {
    _id: 'acc-507',
    name: 'Michael Kors Jet Set Travel Tote Bag',
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=800&auto=format&fit=crop',
    description: 'Spacious signature logo tote with zip-top closure, multiple interior pockets and crossbody strap.',
    category: 'Accessories',
    brand: 'Michael Kors',
    price: 169.99,
    originalPrice: 218.00,
    discount: 22,
    rating: 4.7,
    numReviews: 198,
    countInStock: 12,
    tags: ['accessories', 'bag', 'tote', 'michael kors', 'travel'],
  },

  // ─────────────────────────────────────────────
  // SHOES
  // ─────────────────────────────────────────────
  {
    _id: 'shoe-601',
    name: 'Nike Air Max 270 Athletic Running Sneakers',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=800&auto=format&fit=crop',
    description: 'First-ever Max Air unit created specifically for Nike Sportswear for incredible cushioning.',
    category: 'Shoes',
    brand: 'Nike',
    price: 129.99,
    originalPrice: 160.00,
    discount: 18,
    rating: 4.8,
    numReviews: 450,
    countInStock: 30,
    tags: ['shoes', 'sneakers', 'nike', 'running', 'footwear'],
  },
  {
    _id: 'shoe-602',
    name: 'Clarks Premium Handcrafted Leather Oxford Dress Shoes',
    image: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?q=80&w=800&auto=format&fit=crop',
    description: 'Full-grain polished leather formal shoes with OrthoLite high-comfort footbed.',
    category: 'Shoes',
    brand: 'Clarks',
    price: 119.99,
    originalPrice: 149.99,
    discount: 20,
    rating: 4.7,
    numReviews: 130,
    countInStock: 16,
    tags: ['shoes', 'formal', 'leather', 'oxford', 'footwear'],
  },
  {
    _id: 'shoe-603',
    name: 'Adidas Ultraboost 23 Running Shoes',
    image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?q=80&w=800&auto=format&fit=crop',
    description: 'Linear Energy Push & Boost midsole for a responsive, energized run.',
    category: 'Shoes',
    brand: 'Adidas',
    price: 169.99,
    originalPrice: 199.99,
    discount: 15,
    rating: 4.9,
    numReviews: 390,
    countInStock: 20,
    tags: ['shoes', 'sneakers', 'adidas', 'running', 'boost', 'footwear'],
  },
  {
    _id: 'shoe-604',
    name: "Puma Velocity Nitro Men's Running Shoes",
    image: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?q=80&w=800&auto=format&fit=crop',
    description: 'Nitrogen-infused foam cushioning for superior performance running.',
    category: 'Shoes',
    brand: 'Puma',
    price: 99.99,
    originalPrice: 119.99,
    discount: 17,
    rating: 4.6,
    numReviews: 215,
    countInStock: 18,
    tags: ['shoes', 'running', 'puma', 'sportswear', 'footwear'],
  },
  {
    _id: 'shoe-605',
    name: 'Converse Chuck Taylor All Star High Top Sneakers',
    image: 'https://images.unsplash.com/photo-1463100099107-aa0980c362e6?q=80&w=800&auto=format&fit=crop',
    description: 'Iconic canvas high-top sneakers with medial eyelets and signature star patch.',
    category: 'Shoes',
    brand: 'Converse',
    price: 59.99,
    originalPrice: 75.00,
    discount: 20,
    rating: 4.7,
    numReviews: 670,
    countInStock: 32,
    tags: ['shoes', 'sneakers', 'converse', 'casual', 'footwear'],
  },
  {
    _id: 'shoe-606',
    name: 'Timberland Premium 6-Inch Waterproof Boots',
    image: 'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?q=80&w=800&auto=format&fit=crop',
    description: 'Iconic waterproof nubuck leather boots with seam-sealed construction and lug outsole.',
    category: 'Shoes',
    brand: 'Timberland',
    price: 179.99,
    originalPrice: 219.99,
    discount: 18,
    rating: 4.8,
    numReviews: 320,
    countInStock: 10,
    tags: ['shoes', 'boots', 'timberland', 'waterproof', 'footwear'],
  },

  // ─────────────────────────────────────────────
  // ELECTRONICS
  // ─────────────────────────────────────────────
  {
    _id: 'elec-701',
    name: 'Sony WH-1000XM5 Wireless Noise Canceling Headphones',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800&auto=format&fit=crop',
    description: 'Magnificent sound clarity with two processors and 8 microphones for world-class ANC.',
    category: 'Electronics',
    brand: 'Sony',
    price: 349.99,
    originalPrice: 399.99,
    discount: 12,
    rating: 4.9,
    numReviews: 780,
    countInStock: 22,
    tags: ['electronics', 'headphones', 'sony', 'audio', 'bluetooth'],
  },
  {
    _id: 'elec-702',
    name: 'Apple iPhone 15 Pro Titanium (256GB)',
    image: 'https://images.unsplash.com/photo-1696446701796-da61225697cc?q=80&w=800&auto=format&fit=crop',
    description: 'A17 Pro chip, customizable Action button, aerospace-grade titanium design.',
    category: 'Electronics',
    brand: 'Apple',
    price: 999.99,
    originalPrice: 1099.99,
    discount: 9,
    rating: 4.9,
    numReviews: 1250,
    countInStock: 10,
    tags: ['electronics', 'mobile', 'apple', 'smartphone', 'ios'],
  },
  {
    _id: 'elec-703',
    name: 'Samsung Galaxy S24 Ultra 5G (512GB)',
    image: 'https://images.unsplash.com/photo-1707028169135-26330089dbbc?q=80&w=800&auto=format&fit=crop',
    description: 'Galaxy AI redefines mobile intelligence with built-in S-Pen and 200MP camera.',
    category: 'Electronics',
    brand: 'Samsung',
    price: 1199.99,
    originalPrice: 1399.99,
    discount: 14,
    rating: 4.8,
    numReviews: 960,
    countInStock: 12,
    tags: ['electronics', 'mobile', 'samsung', 'android', 'smartphone'],
  },
  {
    _id: 'elec-704',
    name: 'iPad Pro 12.9" M2 Wi-Fi (256GB)',
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?q=80&w=800&auto=format&fit=crop',
    description: 'Extreme performance with M2 chip, Liquid Retina XDR display and Apple Pencil support.',
    category: 'Electronics',
    brand: 'Apple',
    price: 1099.99,
    originalPrice: 1299.00,
    discount: 15,
    rating: 4.9,
    numReviews: 540,
    countInStock: 8,
    tags: ['electronics', 'tablet', 'apple', 'ipad', 'pro'],
  },
  {
    _id: 'elec-705',
    name: 'JBL Flip 6 Portable Waterproof Bluetooth Speaker',
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?q=80&w=800&auto=format&fit=crop',
    description: 'IP67-waterproof portable speaker with 12hr battery and powerful JBL Pro Sound.',
    category: 'Electronics',
    brand: 'JBL',
    price: 109.99,
    originalPrice: 129.99,
    discount: 15,
    rating: 4.7,
    numReviews: 470,
    countInStock: 25,
    tags: ['electronics', 'speaker', 'jbl', 'bluetooth', 'waterproof'],
  },
  {
    _id: 'elec-706',
    name: 'Dell XPS 15 Laptop (Core i9, 32GB, RTX 4070)',
    image: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?q=80&w=800&auto=format&fit=crop',
    description: 'OLED 4K display, 13th Gen Core i9, and NVIDIA RTX 4070 for ultimate creative performance.',
    category: 'Electronics',
    brand: 'Dell',
    price: 2299.99,
    originalPrice: 2599.99,
    discount: 12,
    rating: 4.8,
    numReviews: 230,
    countInStock: 5,
    tags: ['electronics', 'laptop', 'dell', 'computer', 'xps'],
  },

  // ─────────────────────────────────────────────
  // PERFUMES
  // ─────────────────────────────────────────────
  {
    _id: 'perf-801',
    name: 'Bleu de Chanel Eau de Parfum Spray (100ml)',
    image: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?q=80&w=800&auto=format&fit=crop',
    description: 'Captivating woody aromatic fragrance with fresh citrus and amber drydown.',
    category: 'Perfumes',
    brand: 'Chanel',
    price: 125.00,
    originalPrice: 150.00,
    discount: 17,
    rating: 4.9,
    numReviews: 620,
    countInStock: 25,
    tags: ['perfumes', 'fragrance', 'chanel', 'woody', 'luxury'],
  },
  {
    _id: 'perf-802',
    name: 'Dior Sauvage Elixir Intense Cologne (60ml)',
    image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?q=80&w=800&auto=format&fit=crop',
    description: 'Extraordinarily concentrated fragrance steeped in the iconic freshness of Sauvage.',
    category: 'Perfumes',
    brand: 'Dior',
    price: 135.00,
    originalPrice: 165.00,
    discount: 18,
    rating: 4.9,
    numReviews: 810,
    countInStock: 20,
    tags: ['perfumes', 'cologne', 'dior', 'masculine', 'luxury'],
  },
  {
    _id: 'perf-803',
    name: 'YSL Black Opium Eau de Parfum (90ml)',
    image: 'https://images.unsplash.com/photo-1587017539504-67cfbddac569?q=80&w=800&auto=format&fit=crop',
    description: 'Addictive coffee and vanilla gourmand fragrance with sensual white floral notes.',
    category: 'Perfumes',
    brand: 'YSL',
    price: 99.99,
    originalPrice: 118.00,
    discount: 15,
    rating: 4.8,
    numReviews: 530,
    countInStock: 22,
    tags: ['perfumes', 'fragrance', 'ysl', 'coffee', 'feminine'],
  },
  {
    _id: 'perf-804',
    name: 'Giorgio Armani Acqua di Gio Profondo (75ml)',
    image: 'https://images.unsplash.com/photo-1615634260167-c8cdede054de?q=80&w=800&auto=format&fit=crop',
    description: 'Deep aquatic marine fragrance inspired by the depths of the Mediterranean Sea.',
    category: 'Perfumes',
    brand: 'Armani',
    price: 89.99,
    originalPrice: 110.00,
    discount: 18,
    rating: 4.8,
    numReviews: 390,
    countInStock: 18,
    tags: ['perfumes', 'cologne', 'armani', 'aquatic', 'marine'],
  },
  {
    _id: 'perf-805',
    name: 'Tom Ford Tobacco Vanille Eau de Parfum (50ml)',
    image: 'https://images.unsplash.com/photo-1563170351-be82bc888aa4?q=80&w=800&auto=format&fit=crop',
    description: 'Opulent blend of tobacco leaf, tonka bean, vanilla and cacao. Rich, warm and luxurious.',
    category: 'Perfumes',
    brand: 'Tom Ford',
    price: 189.99,
    originalPrice: 230.00,
    discount: 17,
    rating: 4.9,
    numReviews: 280,
    countInStock: 10,
    tags: ['perfumes', 'fragrance', 'tom ford', 'vanilla', 'luxury', 'unisex'],
  },

  // ─────────────────────────────────────────────
  // CHOCOLATES
  // ─────────────────────────────────────────────
  {
    _id: 'choc-901',
    name: 'Lindt Swiss Luxury Gourmet Chocolate Selection (300g)',
    image: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?q=80&w=800&auto=format&fit=crop',
    description: 'Master Swiss chocolatier crafted milk, dark, and hazelnut praline chocolates gift box.',
    category: 'Chocolates',
    brand: 'Lindt',
    price: 21.99,
    originalPrice: 29.99,
    discount: 27,
    rating: 4.9,
    numReviews: 380,
    countInStock: 60,
    tags: ['chocolates', 'swiss', 'lindt', 'gift', 'luxury', 'truffles'],
  },
  {
    _id: 'choc-902',
    name: 'Godiva Artisanal Dark Chocolate Truffles Gift Set (24 pcs)',
    image: 'https://images.unsplash.com/photo-1511381939415-e44015466834?q=80&w=800&auto=format&fit=crop',
    description: 'Rich 72% cocoa Belgian dark chocolate truffles with velvety ganache center.',
    category: 'Chocolates',
    brand: 'Godiva',
    price: 34.99,
    originalPrice: 44.99,
    discount: 22,
    rating: 4.9,
    numReviews: 290,
    countInStock: 45,
    tags: ['chocolates', 'belgian', 'godiva', 'dark chocolate', 'truffles', 'gift'],
  },
  {
    _id: 'choc-903',
    name: 'Ferrero Rocher Fine Hazelnut Chocolates Box (48 pcs)',
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?q=80&w=800&auto=format&fit=crop',
    description: 'Whole roasted hazelnut in creamy filling, wafer shell, and chopped hazelnuts coating.',
    category: 'Chocolates',
    brand: 'Ferrero',
    price: 24.99,
    originalPrice: 32.99,
    discount: 24,
    rating: 4.8,
    numReviews: 640,
    countInStock: 80,
    tags: ['chocolates', 'hazelnut', 'ferrero', 'milk chocolate', 'gift'],
  },
  {
    _id: 'choc-904',
    name: 'Cadbury Celebrations Assorted Chocolate Gift Pack (281g)',
    image: 'https://images.unsplash.com/photo-1481391319762-47dff72954d9?q=80&w=800&auto=format&fit=crop',
    description: 'Assortment of miniature Cadbury favourites — Dairy Milk, 5-Star, Gems, Eclairs.',
    category: 'Chocolates',
    brand: 'Cadbury',
    price: 12.99,
    originalPrice: 17.99,
    discount: 28,
    rating: 4.6,
    numReviews: 950,
    countInStock: 100,
    tags: ['chocolates', 'cadbury', 'dairy milk', 'assorted', 'gift', 'milk chocolate'],
  },
  {
    _id: 'choc-905',
    name: 'Thorntons Classic Collection Gift Box (262g)',
    image: 'https://images.unsplash.com/photo-1575377222312-dd1a63a51638?q=80&w=800&auto=format&fit=crop',
    description: 'Premium selection of toffees, pralines, truffles and caramels in a beautiful keepsake box.',
    category: 'Chocolates',
    brand: 'Thorntons',
    price: 16.99,
    originalPrice: 22.99,
    discount: 26,
    rating: 4.7,
    numReviews: 180,
    countInStock: 55,
    tags: ['chocolates', 'assorted', 'thorntons', 'toffee', 'caramel', 'gift'],
  },
];
